name: App Links Audit Bot

on:
  workflow_dispatch:
  schedule:
    - cron: "0,15,30,45 * * * *"

jobs:
  run-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Create Credentials File
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > src/credentials.json

      - name: Run Audit Script
        run: node src/index.js
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
